version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-7
  rubocop:
    enabled: true
    channel: rubocop-1-9-1
  sass-lint:
    enabled: true
exclude_patterns:
- spec/
- vendor/asset/

- app/javascript/mastodon/locales/**/*.json
- config/locales/**/*.yml
