blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/mastodon/mastodon/discussions
    about: Please ask and answer questions here.
  - name: Bug Bounty Program
    url: https://app.intigriti.com/programs/mastodon/mastodonio/detail
    about: Please report security vulnerabilities here.
