---
ja:
  admin:
    dashboard:
      keybase: Keybase統合
    settings:
      enable_keybase:
        desc_html: Keybaseにより身元の証明が可能となります
        title: Keybase統合を有効にする
      outgoing_spoilers:
        desc_html: トゥートが連合される際、閲覧注意としてマークされていないトゥートにこの警告が追加されます。これはあなたのインスタンスが他のインスタンスに警告をして欲しいとされる投稿に特化している場合に便利です。 メディアは閲覧注意にマークされます。
        title: 発信するトゥートへの警告
      hide_followers_count:
        desc_html: プロフィールページのフォロワー数を見られないようにします
        title: フォロワー数を隠す
      show_reblogs_in_public_timelines:
        desc_html: ローカルタイムラインと連合タイムラインに公開投稿のブーストを表示します
        title: 公開タイムラインにブーストを表示
      show_replies_in_public_timelines:
        desc_html: 自分への公開投稿の返信に加えて、すべての公開投稿の返信をローカルタイムラインと連合タイムラインに表示します。
        title: 公開タイムラインに返信を表示
  generic:
    use_this: これを使う
  settings:
    flavours: フレーバー
