---
ko:
  admin:
    custom_emojis:
      batch_copy_error: '선택된 에모지를 복사하던 중 오류가 발생했습니다: %{message}'
      batch_error: '에러가 발생했습니다: %{message}'
    domain_allows:
      export: 내보내기
      import: 불러오기
    domain_blocks:
      export: 내보내기
      import: 불러오기
    export_domain_allows:
      new:
        title: 도메인 허용 불러오기
      no_file: 파일이 선택되지 않았습니다
    export_domain_blocks:
      import:
        description_html: 도메인 차단 목록을 불러오려고 합니다. 이 목록을 조심스럽게 검토하세요, 특히 자신이 직접 작성한 목록이 아니라면 더 조심하세요.
        existing_relationships_warning: 팔로우 관계가 존재합니다
        private_comment_description_html: '어디서 불러온 것인지 추적을 원활하게 하기 위해서, 불러온 차단들은 다음과 같은 비공개 주석과 함께 생성될 것입니다: <q>%{comment}</q>'
        private_comment_template: '%{date}에 %{source}에서 불러옴'
        title: 도메인 차단 불러오기
      new:
        title: 도메인 차단 불러오기
      no_file: 파일이 선택되지 않았습니다
    settings:
      captcha_enabled:
        desc_html: 이것은 hCaptcha의 외부 스크립트에 의존합니다, 이것은 개인정보 보호에 위협을 가할 수도 있습니다. 추가적으로, <strong>이것은 몇몇 사람들(특히나 장애인들)에게 가입 절차의 접근성을 심각하게 떨어트릴 수 있습니다</strong>. 이러한 이유로, 대체제로 승인 전용이나 초대제를 통한 가입을 고려해보세요.<br>한정된 사용만 가능한 초대장을 통한 가입자들은 CAPTCHA를 풀지 않아도 됩니다
        title: 새로운 사용자가 계정 확인을 위해서는 CAPTCHA를 풀어야 하도록 합니다
      hide_followers_count:
        desc_html: 사용자 프로필에 팔로워 수를 표시하지 않습니다
        title: 팔로워 수 숨기기
      show_reblogs_in_public_timelines:
        desc_html: 공개글의 공개적인 부스트를 로컬과 공개 타임라인에 표시합니다.
        title: 부스트를 공개 타임라인에 표시
      show_replies_in_public_timelines:
        desc_html: 자기자신에 대한 답글(글타래)와 마찬가지로, 공개적인 답글을 로컬과 공개 타임라인에 표시합니다.
        title: 답글을 공개 타임라인에 표시
      trending_status_cw:
        desc_html: 유행하는 게시물이 활성화 되었을 때, 열람주의가 설정된 글도 허용합니다. 이 설정의 변경은 소급 적용되지 않습니다.
        title: 열람주의를 가진 글이 유행에 오를 수 있도록 허용
  auth:
    captcha_confirmation:
      hint_html: 한가지 단계가 남았습니다! 계정을 확인하기 위해서는, CAPTCHA를 풀어야 합니다. 질문이 있거나 계정 확인 과정에서 도움을 받고 싶은 경우 <a href="/about/more">서버의 관리자에게 연락해서</a> 해결할 수 있습니다.
      title: 사용자 확인
  generic:
    use_this: 사용하기
  settings:
    flavours: 풍미
