---
zh-CN:
  simple_form:
    hints:
      defaults:
        setting_default_content_type_html: 在撰写嘟文时，除非另有指定，假定它们使用原始 HTML 语言撰写
        setting_default_content_type_markdown: 在撰写嘟文时，除非另有指定，假定它们使用 Markdown 进行富文本格式化
        setting_default_content_type_plain: 在撰写嘟文时，除非另有指定，假定它们是没有特殊格式的纯文本（默认的 Mastodon 行为）
        setting_default_language: 你的嘟文语言可以自动检测，但不一定准确
        setting_skin: 更换为所选择的 Mastodon 风味
    labels:
      defaults:
        setting_default_content_type: 嘟文的默认格式
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: 纯文本
        setting_favourite_modal: 在喜欢嘟文前询问我 (仅限于 Glitch 风味)
        setting_hide_followers_count: 隐藏你的关注者人数
        setting_skin: 皮肤
        setting_system_emoji_font: 表情符号使用系统默认字体 (仅限于 Glitch 风味)